"""Shared test fixtures.

Every test runs against a **temporary** data dir (so we never touch the real
``%LOCALAPPDATA%\\YotoMaker``), and gets a real short MP3 generated by ffmpeg for
integration tests. Tests that need ffmpeg are skipped automatically if it's not
installed.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from yoto_maker import config as config_mod
from yoto_maker.config import Config, set_config
from yoto_maker.tools import find_ffmpeg

REPO_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def temp_config(tmp_path, monkeypatch):
    """Point the app at a temp data dir; keep bundle_root at the repo root."""
    # Client ID is resolved live from env → settings → default, so set it here.
    monkeypatch.setenv("YOTO_CLIENT_ID", "test_client_id")
    cfg = Config(
        data_dir=tmp_path / "data",
        bundle_root=REPO_ROOT,
        yoto_client_id="test_client_id",
        host="127.0.0.1",
        port=8799,
    )
    cfg.ensure_dirs()
    set_config(cfg)
    yield cfg
    set_config(None)  # reset singleton between tests


@pytest.fixture
def sample_mp3(temp_config, tmp_path) -> Path:
    """A real 2-second MP3 with a title tag, made by ffmpeg.

    Placed in an 'incoming' dir (like a file on the user's computer), NOT the
    app work dir, so adapters exercise the real copy path.
    """
    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        pytest.skip("ffmpeg not available")
    incoming = tmp_path / "incoming"
    incoming.mkdir(parents=True, exist_ok=True)
    out = incoming / "sample.mp3"
    subprocess.run(
        [ffmpeg, "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
         "-metadata", "title=Sample Song", str(out)],
        capture_output=True, check=True,
    )
    return out


@pytest.fixture
def has_ffmpeg() -> bool:
    if not find_ffmpeg():
        pytest.skip("ffmpeg not available")
    return True
